apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chrome
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kuratajr/chrome-idx.git
    targetRevision: HEAD
    path: chrome
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
