apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: longhorn.io/node
                    operator: In
                    values:
                      - "true"
      containers:
        - name: chrome
          image: lscr.io/linuxserver/brave:latest
          ports:
            - containerPort: 3000
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Ho_Chi_Minh"
            - name: CHROME_OPTS
              value: "--no-sandbox --disable-dev-shm-usage"
          volumeMounts:
            - name: chrome-storage
              mountPath: /config
      volumes:
        - name: chrome-storage
          persistentVolumeClaim:
            claimName: chrome-config
